name: PostSubmit
on: push
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 5.x
      - name: install gulp
        run: npm install -g gulp
      - name: install
        run: npm install
      - name: build dist
        run: npm run dist
      - name: Get the version
        id: get_version
        if: startsWith(github.ref, 'refs/tags/')
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      - name: prepare deploy
        if: startsWith(github.ref, 'refs/tags/')
        run: cd dist && zip -r marathon-ui-${TAG}.zip .
        env:
          TAG: ${{ steps.get_version.outputs.TAG }}
      - name: Create release
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/marathon-ui-${{ steps.get_version.outputs.TAG }}.zip

